### ISSUE TITLE
\global \newcommand that persist across render / renderToString calls

### ISSUE THREAD

**Issue by cirosantilli** [KaTeX/KaTeX#2070]
On KaTeX 0.10.2 the commented line below would fail:

```
#!/usr/bin/env nodejs
var katex = require('katex')
macros = {}
console.log(katex.renderToString("\\gdef\\foo{myfoo}", {macros: macros, throwOnError: true}));
console.log(katex.renderToString("\\foo", {macros: macros, throwOnError: true}));
console.log(katex.renderToString("\\newcommand{\\baz}[0]{mybaz}", {macros: macros, throwOnError: true}));
//console.log(katex.renderToString("\\baz", {macros: macros, throwOnError: true}));
console.log(katex.renderToString("\\newcommand{\\baz}[0]{mybaz}\n\\baz", {macros: macros, throwOnError: true}));
console.log(macros)
```

with error:

```
/home/ciro/test/node_modules/katex/dist/katex.js:16668
    throw error;
    ^

ParseError: KaTeX parse error: Undefined control sequence: \baz at position 1: \̲b̲a̲z̲
    at new ParseError (/home/ciro/test/node_modules/katex/dist/katex.js:261:14)
    at Parser.parseGroup (/home/ciro/test/node_modules/katex/dist/katex.js:16326:17)
    at Parser.parseAtom (/home/ciro/test/node_modules/katex/dist/katex.js:15789:21)
    at Parser.parseExpression (/home/ciro/test/node_modules/katex/dist/katex.js:15650:23)
    at Parser.parse (/home/ciro/test/node_modules/katex/dist/katex.js:15618:22)
    at parseTree (/home/ciro/test/node_modules/katex/dist/katex.js:16579:21)
    at renderToDomTree (/home/ciro/test/node_modules/katex/dist/katex.js:16686:16)
    at Object.renderToString (/home/ciro/test/node_modules/katex/dist/katex.js:16647:16)
    at Object.<anonymous> (/home/ciro/test/main.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
```

I know about `\global\def` and `\gdef`, but `\newcommand` is much more common.

I've seen the discussion at: https://github.com/KaTeX/KaTeX/pull/1382#issuecomment-396804705 but decided to create a new issue to better focus on the problem.

There is some LaTeX talk about this at: https://groups.google.com/forum/#!topic/comp.text.tex/rm__irFVbuw but I don't mind if we follow LaTeX or not here, e.g. why not either:

- make every definition persist across blocks by default and get rid of `\global`. Why isn't that the default behavior?
- invent a new `\gnewcomand`

My motivation for this is that I'm integrating Asciidoctor with KaTeX to achieve HTML Math Nirvana: https://github.com/asciidoctor/asciidoctor/pull/3338

But so far this feature alone makes me want to fall back on MathJax I think :-(

**Comment by edemaine** [comment]
Our general goal in KaTeX is compatibility with LaTeX.  Sadly, LaTeX doesn't have a global form of `\newcommand`, and creates a group for every math mode, which is why we're in the current state.

I could a few possible ways to improve the situation:
1. We could add a `render` option called something like `globalGroup` which runs the expression in the global group, instead of creating a math group like LaTeX does.  This could be used specifically for blocks that define macros, or could be set on all blocks to simulate MathJax behavior.
2. Perhaps we could define something like a `\begin{macros}...\end{macros}` environment via #2042 that would automatically happen in the global group.  I'm not sure how that would be done in LaTeX though, as `\begin` always creates a group...
3. As you suggest, we could make something like `\gnewcommand` or `\global\newcommand`, and perhaps add it to the hypothetical `katex.sty` (#793).  It would be great if there were any precedent for the name of such a command...

Thoughts on which one(s) would be best?

**Comment by cirosantilli** [comment]
Erik,

Option 1 sound great to me! As you say, I would just enable it on every block to replicate MathJax.

About the macro definition on API, I was aware of that and I'm [already using it to propagate `\def` macros across asciidoctor math blocks](https://github.com/cirosantilli/cirosantilli.github.io/blob/9c963c129c311db791f6c0dad6400322b0ab7537/katex.rb#L65).

But it would be awesome if you could explain at `macros` section in https://katex.org/docs/options.html how to implement macros with arguments (there is a link to source, but it takes some time for my brain to parse that :-)) I would give an example:

> Each macro is a property with a name like \name (written "\\name" in JavaScript) which maps to a string that describes the expansion of the macro, or a function that accepts an instance of MacroExpander as first argument and returns the expansion as a string.

> For example, to define a macro that takes two arguments you can use:

> ```
> "\\foo": "my #1 favorite #2 foo"
> ```

> where the number of parameters is deduced from the `#1`, `#2`, etc. in the expansion itself.

This would have saved 30 minutes of my life :-)

**Comment by cirosantilli** [comment]
How do you develop this package? `yarn build && nodejs mytest.js` with `var katex = require('.')` in `mytest.js` works but takes a while in the `yarn build`, any way to speed that up?

**Comment by edemaine** [comment]
@cirosantilli `require('katex')` might work without building.

**Comment by cirosantilli** [comment]
`require('katex')` gives:

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'katex'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/ciro/git/KaTeX/main.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

and `var katex = require('./katex.js')` gives:

```
/home/ciro/git/KaTeX/katex.js:11
import ParseError from "./src/ParseError";
       ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by edemaine** [comment]
You would need to enable Node's support for `import` (a command-line option in Node 12). Obviously untested...

If you're looking to write tests, it'd be better to add them directly to the Jest tests. These run (via `yarn test:jest`) withour buiilding. Also there's a tool for interactive experimentation via `yarn start`; that's how I usually develop. It autobuilds as you change source files.
