### ISSUE TITLE
yarn start doesn't work anymore?

### ISSUE THREAD

**Issue by edemaine** [KaTeX/KaTeX#2948]
Does `yarn start` still work for other devs?  I get the following error:

```
C:\...\KaTeX\.yarn\$$virtual\webpack-virtual-638a34bb34\0\cache\webpack-npm-5.33.2-4831fb3d39-2132ec24db.zip\node_modules\webpack\lib\NormalModule.js:1059
                return this.generator.getTypes(this);

TypeError: Cannot read property 'getTypes' of undefined
    at NormalModule.getSourceTypes (C:\...\KaTeX\.yarn\$$virtual\webpack-virtual-638a34bb34\0\cache\webpack-npm-5.33.2-4831fb3d39-2132ec24db.zip\node_modules\webpack\lib\NormalModule.js:1059:25)
    at _ (C:\...\KaTeX\.yarn\$$virtual\webpack-virtual-638a34bb34\0\cache\webpack-npm-5.33.2-4831fb3d39-2132ec24db.zip\node_modules\webpack\lib\stats\DefaultStatsFactoryPlugin.js:1086:36)
    at C:\...\KaTeX\.yarn\$$virtual\webpack-virtual-638a34bb34\0\cache\webpack-npm-5.33.2-4831fb3d39-2132ec24db.zip\node_modules\webpack\lib\stats\DefaultStatsFactoryPlugin.js:2245:9
    at Hook.eval [as call] (eval at create (C:\...\KaTeX\.yarn\cache\tapable-npm-2.2.0-516ee6aa5b-f8ed725aed.zip\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:16)
    at C:\...\KaTeX\.yarn\$$virtual\webpack-virtual-638a34bb34\0\cache\webpack-npm-5.33.2-4831fb3d39-2132ec24db.zip\node_modules\webpack\lib\stats\StatsFactory.js:277:7
    at StatsFactory._forEachLevel (C:\...\KaTeX\.yarn\$$virtual\webpack-virtual-638a34bb34\0\cache\webpack-npm-5.33.2-4831fb3d39-2132ec24db.zip\node_modules\webpack\lib\stats\StatsFactory.js:100:19)
    at StatsFactory._create (C:\...\KaTeX\.yarn\$$virtual\webpack-virtual-638a34bb34\0\cache\webpack-npm-5.33.2-4831fb3d39-2132ec24db.zip\node_modules\webpack\lib\stats\StatsFactory.js:276:9)
    at StatsFactory.create (C:\...\KaTeX\.yarn\$$virtual\webpack-virtual-638a34bb34\0\cache\webpack-npm-5.33.2-4831fb3d39-2132ec24db.zip\node_modules\webpack\lib\stats\StatsFactory.js:137:16)
    at C:\...\KaTeX\.yarn\$$virtual\webpack-virtual-638a34bb34\0\cache\webpack-npm-5.33.2-4831fb3d39-2132ec24db.zip\node_modules\webpack\lib\stats\StatsFactory.js:215:24
    at Array.map (<anonymous>)
```

Out of habit, I tried `npm install` and `npm start` and this actually worked fine.  So perhaps I'm just using Yarn incorrectly?  `yarn --version` reports 2.2.0.  (I do wonder whether it's still worth sticking with Yarn, given the many improvements to NPM in recent years.)

**Comment by ylemkimon** [comment]
Have you run `yarn install` before `yarn start`?

**Comment by edemaine** [comment]
Yes. I've deleted `node_modules` and `.yarn/cache`, run `yarn`, and `yarn start` produces the above error message after a few seconds and the positive message `<i> [webpack-dev-middleware] Compiled successfully.`.  I've tried a few times.

Possibly relevant: Before this error message, I get a bunch of messages like
```
Watchpack Error (initial scan): Error: EACCES: permission denied, lstat 'C:\Users\edemaine\.latexmkrc'
Watchpack Error (initial scan): Error: EACCES: permission denied, lstat 'C:\Users\edemaine\.minttyrc'
```

It's a little weird that Watchpack is looking at these files... (They are Cygwin symlinks so they can't be accessed within Node.)

**Comment by ronkok** [comment]
`yarn start` does not work for me either.

**Comment by ylemkimon** [comment]
I could reproduce the issue on my Windows machine, however I cannot pinpoint the source of the issue. It seems like webpack or webpack-dev-server issue and I've opened https://github.com/webpack/webpack-dev-server/issues/3235.

**Comment by edemaine** [comment]
As reported in https://github.com/webpack/webpack-dev-server/issues/3235, this was fixed in a recent update to webpack. I confirmed that I no longer have issues with KaTeX's master branch.
