### ISSUE TITLE
Screenshotter can't do specific browser

### ISSUE THREAD

**Issue by edemaine** [KaTeX/KaTeX#3383]
**Describe the bug:**
`dockers/screenshotter/screenshotter.sh` (and `.js`) supports a `-b` option. It seems to stop the screenshot for other browsers from working, but doesn't actually stop the attempt of screenshotting.

**To Reproduce:**
```
$ cd dockers/screenshotter
$ ./screenshotter.sh -i VerticalSpacing -b chrome
Starting container for selenium/standalone-firefox:3.141.59-20210929
Container 969a107404cb started, creating screenshots...
Selenium driver at http://172.17.0.1:32809/wd/hub
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:39096/
<i> [webpack-dev-server] On Your Network (IPv4): http://...:39096/
<i> [webpack-dev-server] Content not from webpack is served from '.../KaTeX' directory
SessionNotCreatedError: Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '969a107404cb', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-201-generic', java.version: '1.8.0_292'
Driver info: driver.version: unknown
    at Object.checkLegacyResponse (.../KaTeX/.yarn/cache/selenium-webdriver-npm-4.0.0-6998a4ef38-ac9861e9aa.zip/node_modules/selenium-webdriver/lib/error.js:553:15)
    at parseHttpResponse (.../KaTeX/.yarn/cache/selenium-webdriver-npm-4.0.0-6998a4ef38-ac9861e9aa.zip/node_modules/selenium-webdriver/lib/http.js:635:13)
    at Executor.execute (.../KaTeX/.yarn/cache/selenium-webdriver-npm-4.0.0-6998a4ef38-ac9861e9aa.zip/node_modules/selenium-webdriver/lib/http.js:569:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'SessionNotCreatedError',
  remoteStacktrace: ''
}
Failed taking screenshots, stopping and removing 969a107404cb
Starting container for selenium/standalone-chrome:3.141.59-20210422
Container 496cef7f248d started, creating screenshots...
Selenium driver at http://172.17.0.1:32810/wd/hub
... the Chrome execution works fine ...
```

**Expected behavior:**
I expect the output starting with `Starting container for selenium/standalone-chrome:3.141.59-20210422`

**Environment (please complete the following information):**
 - KaTeX Version: main branch
 - Device: Desktop
 - OS: Ubuntu
 - Browser: Node

**Additional context:**
Not a big deal; just for speeding up certain checks. Perhaps a side effect of @ylemkimon recent rewrite to use async?

**Comment by ylemkimon** [comment]
`screenshotter.sh` doesn't support specifying the browser, but yes, it'd be useful.
